### ISSUE TITLE
Download location might cause issues

### ISSUE THREAD

**Issue by elsaware** [tytydraco/Trackophile#1]
According to the readme, the software saves in /Android/Data/<app name>. This causes 2 problems :
1. Going to /Android/Data is not intuitive for the average user, and music players do not scan the /Android folder and subfolders. 
2. Starting with Android 11, the /Android/data folder is no longer accessible to software excepted the stock Android explorer, which is usually hidden in settings or made unaccessible.

The easiest way to deal with this issue would be to request Storage permissions and save the content to /Music/ (or a subfolder).

**Comment by elsaware** [comment]
I should add that most software writes stuff to /Android/data, making it really hard to browse for the average user.

**Comment by tytydraco** [comment]
Good point, I'll work on this. Thanks for the suggestion!

**Comment by tytydraco** [comment]
MediaStore is used to write tracks to /Music now 👍
